name: Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  Website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.x'
    - name: Restore NuGet packages
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --logger trx --results-directory TestResults --collect:"XPlat Code Coverage"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        directory: ./TestResults
        flags: Website
        fail_ci_if_error: true
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: website-test-results
        path: ./TestResults
      if: ${{ always() }} # Always run this step even on failure
  WebClient:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install npm packages
      run: npm ci
      working-directory: ./WebClient
    - name: Build
      run: npm run build
      working-directory: ./WebClient
    - name: Test
      run: npm run test
      working-directory: ./WebClient
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./WebClient/logs/coverage/cobertura.xml
        flags: WebClient
        fail_ci_if_error: true
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: webclient-logs
        path: ./WebClient/logs
      if: ${{ always() }} # Always run this step even on failure
